{"level":"info","message":"Printer Store MCP SSE Server is running on http://localhost:3001/sse","timestamp":"2025-05-18T17:56:31.547Z"}
{"level":"info","message":"/sse","timestamp":"2025-05-18T17:56:31.550Z"}
{"level":"info","message":"/messages","timestamp":"2025-05-18T17:56:31.550Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:04.830Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:05.137Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:07.559Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:13.989Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:16.191Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:18.099Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:19.061Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:19.355Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:19.823Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:20.411Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:21.995Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:23.145Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:24.166Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:24.204Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:24.307Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:25.391Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-18T18:00:26.880Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:00:42.609Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:02:08.017Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:04:24.451Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:07:30.259Z"}
{"level":"info","message":"Printer Store MCP SSE Server is running on http://localhost:3001/sse","timestamp":"2025-05-19T09:10:05.302Z"}
{"level":"info","message":"/sse","timestamp":"2025-05-19T09:10:05.307Z"}
{"level":"info","message":"/messages","timestamp":"2025-05-19T09:10:05.308Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:11:07.652Z"}
{"level":"info","message":"Printer Store MCP SSE Server is running on http://localhost:3001/sse","timestamp":"2025-05-19T09:27:09.684Z"}
{"level":"info","message":"/sse","timestamp":"2025-05-19T09:27:09.690Z"}
{"level":"info","message":"/messages","timestamp":"2025-05-19T09:27:09.691Z"}
{"level":"info","message":"Printer Store MCP SSE Server is running on http://localhost:3001/sse","timestamp":"2025-05-19T09:28:43.772Z"}
{"level":"info","message":"/sse","timestamp":"2025-05-19T09:28:43.777Z"}
{"level":"info","message":"/messages","timestamp":"2025-05-19T09:28:43.779Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:36:32.541Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:36:32.559Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:36:32.561Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:40:30.340Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:48:53.307Z"}
{"level":"info","message":"Calling terminal with command: ls /","timestamp":"2025-05-19T09:50:57.729Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:50:57.732Z"}
{"level":"info","message":"Calling terminal with command: ls /home","timestamp":"2025-05-19T09:50:58.592Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:50:58.597Z"}
{"level":"info","message":"Calling terminal with command: ls /","timestamp":"2025-05-19T09:50:59.366Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:50:59.369Z"}
{"level":"info","message":"Calling terminal with command: ls /var","timestamp":"2025-05-19T09:51:01.863Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:51:01.867Z"}
{"level":"info","message":"Calling terminal with command: ls /tmp","timestamp":"2025-05-19T09:51:02.946Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:51:02.950Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:51:05.416Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:51:05.427Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:51:05.429Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:51:05.429Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:51:06.836Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:53:29.199Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T09:59:06.827Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T10:14:54.338Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T10:16:15.952Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T10:16:24.981Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T10:16:24.991Z"}
{"address":"//./pipe/docker_engine","code":"ENOENT","errno":-4058,"level":"error","message":"[callTerminal] Error processing command for session 1: connect ENOENT //./pipe/docker_engine","stack":"Error: connect ENOENT //./pipe/docker_engine\n    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)\n    at __node_internal_exceptionWithHostPort (node:internal/errors:738:12)\n    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)","syscall":"connect","timestamp":"2025-05-19T10:16:24.992Z"}
{"json":{"message":"failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: \"bash\": executable file not found in $PATH: unknown"},"level":"error","message":"[callTerminal] Error processing command for session 1: (HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: \"bash\": executable file not found in $PATH: unknown ","stack":"Error: (HTTP code 400) unexpected - failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: \"bash\": executable file not found in $PATH: unknown \n    at /home/luki/WebstormProjects/cortx/cortx-compute/node_modules/docker-modem/lib/modem.js:383:17\n    at getCause (/home/luki/WebstormProjects/cortx/cortx-compute/node_modules/docker-modem/lib/modem.js:418:7)\n    at Modem.buildPayload (/home/luki/WebstormProjects/cortx/cortx-compute/node_modules/docker-modem/lib/modem.js:379:5)\n    at IncomingMessage.<anonymous> (/home/luki/WebstormProjects/cortx/cortx-compute/node_modules/docker-modem/lib/modem.js:347:16)\n    at IncomingMessage.emit (node:events:530:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","statusCode":400,"timestamp":"2025-05-20T10:45:02.055Z"}
